### ISSUE TITLE
How to add menu to custom navigation page ?

### ISSUE THREAD

**Issue by RocStone** [iissnan/hexo-theme-next#1638]
## Normal page will get a awesome menu in sidebar like this
![urn scniz 0 wq6sl 9v r](https://cloud.githubusercontent.com/assets/13502763/25556207/44ce9430-2d2b-11e7-9132-3db46143b1a8.png)

## But I add a custom navigation page like this
![080b2 t_ 33 c qw3c1](https://cloud.githubusercontent.com/assets/13502763/25556213/6797ba5a-2d2b-11e7-9233-93544be311c9.png)

## And the page at here do not have menu
![s usefkt x9mhvcc5mq_zg](https://cloud.githubusercontent.com/assets/13502763/25556221/8fab5646-2d2b-11e7-85ed-3fd392f70e69.png)

### NexT Information

Add the  ✔  sign before an item which is affected by this behavior.

NexT Version:

  -  Master
  -  Latest Release
  -  Old version - 

NexT Scheme:
  -  All schemes
  -  Muse
  -  Mist
  -  Pisces

**Comment by ivan-nginx** [comment]
@RocStone this custom page may add in `layout/_custom/sidebar.swig`. You can add any html there. See [Part 3. Custom layout code](https://github.com/iissnan/hexo-theme-next/pull/1175) how to use it.

If issue resolved, close it.

**Comment by RocStone** [comment]
@ivan-nginx 
i modified _macro/sidebar.swig，
![w9smj4sqilbn7rc albzon](https://cloud.githubusercontent.com/assets/13502763/25561931/d3cfd9e0-2da9-11e7-8876-07fb1256f9a2.png)

and now custom page can get a menu even it is not in the folder of _post
![18b w_ 8v94bn _0p zfx q](https://cloud.githubusercontent.com/assets/13502763/25561941/40c5d96e-2daa-11e7-89bc-9132d24f4b53.png)

But it brings another problem. 
![8 40se 7cpwtwd2_ ok3ex](https://cloud.githubusercontent.com/assets/13502763/25561949/72d960ce-2daa-11e7-8092-a1513a38a236.png)

Menu button is so close to site overview button, i think this is because css doesn't work some how
And when i clike site overview button, it doesn't work.
Yout can try it at here https://rocstone.github.io/chatter/
## Thank you so much for helping me !

**Comment by ivan-nginx** [comment]
@RocStone what u are doing? I don't understand. U want to appear TOC for Pages too, not only for Posts?

**Comment by RocStone** [comment]
you are right.

**Comment by ivan-nginx** [comment]
@RocStone for now TOC not work for Pages, only for Posts. But, if u want to do something, u may see on `source/js/src` folder and `post-details.js` file. But take care, most of files there are interrelated.

Also, if u can do TOC for Pages, i'll be glad pull request from u.
***
If issue resolved, close it.

**Comment by RocStone** [comment]
@ivan-nginx 
I can switch now.
![w71l wnk g ktk_eq 55 c4](https://cloud.githubusercontent.com/assets/13502763/25660949/0c44d390-3041-11e7-80ae-1e594f85070f.png)
![kfqu9 u dj 22h9s2cmz qp](https://cloud.githubusercontent.com/assets/13502763/25660954/0eac0c0c-3041-11e7-882c-2482ac7d6377.png)
by modify layout/_layout.swig ，I added three lines of code before </body>
![9yj g0ip3hnzpjvzklcn169](https://cloud.githubusercontent.com/assets/13502763/25661079/9ff15a0a-3041-11e7-9a89-74431a18f021.png)
you can verify it at http://rocstone.github.io/chatter/

but still here is problem, these two labels are too close
![m wrwwdrqwtf2qga7g7ai7h](https://cloud.githubusercontent.com/assets/13502763/25661161/f76adf36-3041-11e7-93dd-66ef21cf8ba9.png)
By compare information of two different page in developer mode, i found these
![q84 0_ 92 x3xann a8y](https://cloud.githubusercontent.com/assets/13502763/25661371/e5e3b25a-3042-11e7-8ec7-21065f014d5e.png)
![8uswmw sujn0hn07ul 55n](https://cloud.githubusercontent.com/assets/13502763/25661376/e95b2904-3042-11e7-8d61-6bcc41e0d835.png)
So it is so strange, both of the pages have main.css, but second one can't have a padding. 

Well, I am very glad to push, but i know nothing of node.js, and i am busy with my undergraduate paper, so i maybe will try it sereral month latter. I appreciate your help. Wish you are always happy and luck.

**Comment by ivan-nginx** [comment]
@RocStone issue is solved?

**Comment by cogitoxin** [comment]
same problem here and still waiting for answer

**Comment by youmofangke** [comment]
反映一个问题,当语句块 行数比较大时(上百),首页的行号会溢出

**Comment by RocStone** [comment]
@ivan-nginx not solved totally, the as i showed above, there are too close, pretty ugly.

**Comment by ivan-nginx** [comment]
@RocStone i mean there is pull feature for this: #1649
